//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KACDC.NadaKacheriServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NadaKacheriServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name gscno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_DSC_Status", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponse Get_DSC_Status(KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_DSC_Status", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponse> Get_DSC_StatusAsync(KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest request);
        
        // CODEGEN: Generating message contract since element name GSC_No from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGSCStatus", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.GetGSCStatusResponse GetGSCStatus(KACDC.NadaKacheriServiceReference.GetGSCStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGSCStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetGSCStatusResponse> GetGSCStatusAsync(KACDC.NadaKacheriServiceReference.GetGSCStatusRequest request);
        
        // CODEGEN: Generating message contract since element name GSC_No from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckGSCNumber", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.CheckGSCNumberResponse CheckGSCNumber(KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckGSCNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.CheckGSCNumberResponse> CheckGSCNumberAsync(KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest request);
        
        // CODEGEN: Generating message contract since element name GSC_No from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXmlDataWithDSCV", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponse GetXmlDataWithDSCV(KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXmlDataWithDSCV", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponse> GetXmlDataWithDSCVAsync(KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest request);
        
        // CODEGEN: Generating message contract since element name GSC_No from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXmlDataWoDSCV", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponse GetXmlDataWoDSCV(KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXmlDataWoDSCV", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponse> GetXmlDataWoDSCVAsync(KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest request);
        
        // CODEGEN: Generating message contract since element name RCNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXmlRCDataWODSCV", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponse GetXmlRCDataWODSCV(KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXmlRCDataWODSCV", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponse> GetXmlRCDataWODSCVAsync(KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest request);
        
        // CODEGEN: Generating message contract since element name args from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRCAppTran", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.InsertRCAppTranResponse InsertRCAppTran(KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRCAppTran", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.InsertRCAppTranResponse> InsertRCAppTranAsync(KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest request);
        
        // CODEGEN: Generating message contract since element name args from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRCGSCNo", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponse UpdateRCGSCNo(KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRCGSCNo", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponse> UpdateRCGSCNoAsync(KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest request);
        
        // CODEGEN: Generating message contract since element name AppId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRCAgainstAppId", ReplyAction="*")]
        KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponse UpdateRCAgainstAppId(KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRCAgainstAppId", ReplyAction="*")]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponse> UpdateRCAgainstAppIdAsync(KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_DSC_StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_DSC_Status", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequestBody Body;
        
        public Get_DSC_StatusRequest() {
        }
        
        public Get_DSC_StatusRequest(KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_DSC_StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gscno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashpassed;
        
        public Get_DSC_StatusRequestBody() {
        }
        
        public Get_DSC_StatusRequestBody(string gscno, string hashpassed) {
            this.gscno = gscno;
            this.hashpassed = hashpassed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_DSC_StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_DSC_StatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponseBody Body;
        
        public Get_DSC_StatusResponse() {
        }
        
        public Get_DSC_StatusResponse(KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_DSC_StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_DSC_StatusResult;
        
        public Get_DSC_StatusResponseBody() {
        }
        
        public Get_DSC_StatusResponseBody(string Get_DSC_StatusResult) {
            this.Get_DSC_StatusResult = Get_DSC_StatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGSCStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGSCStatus", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetGSCStatusRequestBody Body;
        
        public GetGSCStatusRequest() {
        }
        
        public GetGSCStatusRequest(KACDC.NadaKacheriServiceReference.GetGSCStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGSCStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GSC_No;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Language;
        
        public GetGSCStatusRequestBody() {
        }
        
        public GetGSCStatusRequestBody(string GSC_No, string Language) {
            this.GSC_No = GSC_No;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGSCStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGSCStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetGSCStatusResponseBody Body;
        
        public GetGSCStatusResponse() {
        }
        
        public GetGSCStatusResponse(KACDC.NadaKacheriServiceReference.GetGSCStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGSCStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetGSCStatusResult;
        
        public GetGSCStatusResponseBody() {
        }
        
        public GetGSCStatusResponseBody(System.Xml.Linq.XElement GetGSCStatusResult) {
            this.GetGSCStatusResult = GetGSCStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckGSCNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckGSCNumber", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.CheckGSCNumberRequestBody Body;
        
        public CheckGSCNumberRequest() {
        }
        
        public CheckGSCNumberRequest(KACDC.NadaKacheriServiceReference.CheckGSCNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckGSCNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GSC_No;
        
        public CheckGSCNumberRequestBody() {
        }
        
        public CheckGSCNumberRequestBody(string GSC_No) {
            this.GSC_No = GSC_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckGSCNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckGSCNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.CheckGSCNumberResponseBody Body;
        
        public CheckGSCNumberResponse() {
        }
        
        public CheckGSCNumberResponse(KACDC.NadaKacheriServiceReference.CheckGSCNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckGSCNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KACDC.NadaKacheriServiceReference.ArrayOfString CheckGSCNumberResult;
        
        public CheckGSCNumberResponseBody() {
        }
        
        public CheckGSCNumberResponseBody(KACDC.NadaKacheriServiceReference.ArrayOfString CheckGSCNumberResult) {
            this.CheckGSCNumberResult = CheckGSCNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlDataWithDSCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlDataWithDSCV", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequestBody Body;
        
        public GetXmlDataWithDSCVRequest() {
        }
        
        public GetXmlDataWithDSCVRequest(KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlDataWithDSCVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GSC_No;
        
        public GetXmlDataWithDSCVRequestBody() {
        }
        
        public GetXmlDataWithDSCVRequestBody(string GSC_No) {
            this.GSC_No = GSC_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlDataWithDSCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlDataWithDSCVResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponseBody Body;
        
        public GetXmlDataWithDSCVResponse() {
        }
        
        public GetXmlDataWithDSCVResponse(KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlDataWithDSCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXmlDataWithDSCVResult;
        
        public GetXmlDataWithDSCVResponseBody() {
        }
        
        public GetXmlDataWithDSCVResponseBody(System.Xml.Linq.XElement GetXmlDataWithDSCVResult) {
            this.GetXmlDataWithDSCVResult = GetXmlDataWithDSCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlDataWoDSCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlDataWoDSCV", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequestBody Body;
        
        public GetXmlDataWoDSCVRequest() {
        }
        
        public GetXmlDataWoDSCVRequest(KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlDataWoDSCVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GSC_No;
        
        public GetXmlDataWoDSCVRequestBody() {
        }
        
        public GetXmlDataWoDSCVRequestBody(string GSC_No) {
            this.GSC_No = GSC_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlDataWoDSCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlDataWoDSCVResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponseBody Body;
        
        public GetXmlDataWoDSCVResponse() {
        }
        
        public GetXmlDataWoDSCVResponse(KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlDataWoDSCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXmlDataWoDSCVResult;
        
        public GetXmlDataWoDSCVResponseBody() {
        }
        
        public GetXmlDataWoDSCVResponseBody(System.Xml.Linq.XElement GetXmlDataWoDSCVResult) {
            this.GetXmlDataWoDSCVResult = GetXmlDataWoDSCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlRCDataWODSCVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlRCDataWODSCV", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequestBody Body;
        
        public GetXmlRCDataWODSCVRequest() {
        }
        
        public GetXmlRCDataWODSCVRequest(KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlRCDataWODSCVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RCNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Dept;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Flag1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Flag2;
        
        public GetXmlRCDataWODSCVRequestBody() {
        }
        
        public GetXmlRCDataWODSCVRequestBody(string RCNo, string Dept, string Flag1, string Flag2) {
            this.RCNo = RCNo;
            this.Dept = Dept;
            this.Flag1 = Flag1;
            this.Flag2 = Flag2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlRCDataWODSCVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlRCDataWODSCVResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponseBody Body;
        
        public GetXmlRCDataWODSCVResponse() {
        }
        
        public GetXmlRCDataWODSCVResponse(KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlRCDataWODSCVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXmlRCDataWODSCVResult;
        
        public GetXmlRCDataWODSCVResponseBody() {
        }
        
        public GetXmlRCDataWODSCVResponseBody(System.Xml.Linq.XElement GetXmlRCDataWODSCVResult) {
            this.GetXmlRCDataWODSCVResult = GetXmlRCDataWODSCVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRCAppTranRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRCAppTran", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.InsertRCAppTranRequestBody Body;
        
        public InsertRCAppTranRequest() {
        }
        
        public InsertRCAppTranRequest(KACDC.NadaKacheriServiceReference.InsertRCAppTranRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRCAppTranRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KACDC.NadaKacheriServiceReference.ArrayOfString args;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Photo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dept;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Flag1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Flag2;
        
        public InsertRCAppTranRequestBody() {
        }
        
        public InsertRCAppTranRequestBody(KACDC.NadaKacheriServiceReference.ArrayOfString args, byte[] Photo, string Dept, string Flag1, string Flag2) {
            this.args = args;
            this.Photo = Photo;
            this.Dept = Dept;
            this.Flag1 = Flag1;
            this.Flag2 = Flag2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRCAppTranResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRCAppTranResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.InsertRCAppTranResponseBody Body;
        
        public InsertRCAppTranResponse() {
        }
        
        public InsertRCAppTranResponse(KACDC.NadaKacheriServiceReference.InsertRCAppTranResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRCAppTranResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement InsertRCAppTranResult;
        
        public InsertRCAppTranResponseBody() {
        }
        
        public InsertRCAppTranResponseBody(System.Xml.Linq.XElement InsertRCAppTranResult) {
            this.InsertRCAppTranResult = InsertRCAppTranResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRCGSCNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRCGSCNo", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequestBody Body;
        
        public UpdateRCGSCNoRequest() {
        }
        
        public UpdateRCGSCNoRequest(KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRCGSCNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KACDC.NadaKacheriServiceReference.ArrayOfString args;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Dept;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Flag1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Flag2;
        
        public UpdateRCGSCNoRequestBody() {
        }
        
        public UpdateRCGSCNoRequestBody(KACDC.NadaKacheriServiceReference.ArrayOfString args, string Dept, string Flag1, string Flag2) {
            this.args = args;
            this.Dept = Dept;
            this.Flag1 = Flag1;
            this.Flag2 = Flag2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRCGSCNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRCGSCNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponseBody Body;
        
        public UpdateRCGSCNoResponse() {
        }
        
        public UpdateRCGSCNoResponse(KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRCGSCNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateRCGSCNoResult;
        
        public UpdateRCGSCNoResponseBody() {
        }
        
        public UpdateRCGSCNoResponseBody(System.Xml.Linq.XElement UpdateRCGSCNoResult) {
            this.UpdateRCGSCNoResult = UpdateRCGSCNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRCAgainstAppIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRCAgainstAppId", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequestBody Body;
        
        public UpdateRCAgainstAppIdRequest() {
        }
        
        public UpdateRCAgainstAppIdRequest(KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRCAgainstAppIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RCNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dept;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Flag1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Flag2;
        
        public UpdateRCAgainstAppIdRequestBody() {
        }
        
        public UpdateRCAgainstAppIdRequestBody(string AppId, string RCNo, string Dept, string Flag1, string Flag2) {
            this.AppId = AppId;
            this.RCNo = RCNo;
            this.Dept = Dept;
            this.Flag1 = Flag1;
            this.Flag2 = Flag2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRCAgainstAppIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRCAgainstAppIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponseBody Body;
        
        public UpdateRCAgainstAppIdResponse() {
        }
        
        public UpdateRCAgainstAppIdResponse(KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRCAgainstAppIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement UpdateRCAgainstAppIdResult;
        
        public UpdateRCAgainstAppIdResponseBody() {
        }
        
        public UpdateRCAgainstAppIdResponseBody(System.Xml.Linq.XElement UpdateRCAgainstAppIdResult) {
            this.UpdateRCAgainstAppIdResult = UpdateRCAgainstAppIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : KACDC.NadaKacheriServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<KACDC.NadaKacheriServiceReference.WebServiceSoap>, KACDC.NadaKacheriServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.Get_DSC_Status(KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest request) {
            return base.Channel.Get_DSC_Status(request);
        }
        
        public string Get_DSC_Status(string gscno, string hashpassed) {
            KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest inValue = new KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequestBody();
            inValue.Body.gscno = gscno;
            inValue.Body.hashpassed = hashpassed;
            KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).Get_DSC_Status(inValue);
            return retVal.Body.Get_DSC_StatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.Get_DSC_StatusAsync(KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest request) {
            return base.Channel.Get_DSC_StatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.Get_DSC_StatusResponse> Get_DSC_StatusAsync(string gscno, string hashpassed) {
            KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest inValue = new KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.Get_DSC_StatusRequestBody();
            inValue.Body.gscno = gscno;
            inValue.Body.hashpassed = hashpassed;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).Get_DSC_StatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.GetGSCStatusResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.GetGSCStatus(KACDC.NadaKacheriServiceReference.GetGSCStatusRequest request) {
            return base.Channel.GetGSCStatus(request);
        }
        
        public System.Xml.Linq.XElement GetGSCStatus(string GSC_No, string Language) {
            KACDC.NadaKacheriServiceReference.GetGSCStatusRequest inValue = new KACDC.NadaKacheriServiceReference.GetGSCStatusRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetGSCStatusRequestBody();
            inValue.Body.GSC_No = GSC_No;
            inValue.Body.Language = Language;
            KACDC.NadaKacheriServiceReference.GetGSCStatusResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetGSCStatus(inValue);
            return retVal.Body.GetGSCStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetGSCStatusResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.GetGSCStatusAsync(KACDC.NadaKacheriServiceReference.GetGSCStatusRequest request) {
            return base.Channel.GetGSCStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetGSCStatusResponse> GetGSCStatusAsync(string GSC_No, string Language) {
            KACDC.NadaKacheriServiceReference.GetGSCStatusRequest inValue = new KACDC.NadaKacheriServiceReference.GetGSCStatusRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetGSCStatusRequestBody();
            inValue.Body.GSC_No = GSC_No;
            inValue.Body.Language = Language;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetGSCStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.CheckGSCNumberResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.CheckGSCNumber(KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest request) {
            return base.Channel.CheckGSCNumber(request);
        }
        
        public KACDC.NadaKacheriServiceReference.ArrayOfString CheckGSCNumber(string GSC_No) {
            KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest inValue = new KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.CheckGSCNumberRequestBody();
            inValue.Body.GSC_No = GSC_No;
            KACDC.NadaKacheriServiceReference.CheckGSCNumberResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).CheckGSCNumber(inValue);
            return retVal.Body.CheckGSCNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.CheckGSCNumberResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.CheckGSCNumberAsync(KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest request) {
            return base.Channel.CheckGSCNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.CheckGSCNumberResponse> CheckGSCNumberAsync(string GSC_No) {
            KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest inValue = new KACDC.NadaKacheriServiceReference.CheckGSCNumberRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.CheckGSCNumberRequestBody();
            inValue.Body.GSC_No = GSC_No;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).CheckGSCNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.GetXmlDataWithDSCV(KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest request) {
            return base.Channel.GetXmlDataWithDSCV(request);
        }
        
        public System.Xml.Linq.XElement GetXmlDataWithDSCV(string GSC_No) {
            KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest inValue = new KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequestBody();
            inValue.Body.GSC_No = GSC_No;
            KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetXmlDataWithDSCV(inValue);
            return retVal.Body.GetXmlDataWithDSCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.GetXmlDataWithDSCVAsync(KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest request) {
            return base.Channel.GetXmlDataWithDSCVAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVResponse> GetXmlDataWithDSCVAsync(string GSC_No) {
            KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest inValue = new KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetXmlDataWithDSCVRequestBody();
            inValue.Body.GSC_No = GSC_No;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetXmlDataWithDSCVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.GetXmlDataWoDSCV(KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest request) {
            return base.Channel.GetXmlDataWoDSCV(request);
        }
        
        public System.Xml.Linq.XElement GetXmlDataWoDSCV(string GSC_No) {
            KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest inValue = new KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequestBody();
            inValue.Body.GSC_No = GSC_No;
            KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetXmlDataWoDSCV(inValue);
            return retVal.Body.GetXmlDataWoDSCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.GetXmlDataWoDSCVAsync(KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest request) {
            return base.Channel.GetXmlDataWoDSCVAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVResponse> GetXmlDataWoDSCVAsync(string GSC_No) {
            KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest inValue = new KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetXmlDataWoDSCVRequestBody();
            inValue.Body.GSC_No = GSC_No;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetXmlDataWoDSCVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.GetXmlRCDataWODSCV(KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest request) {
            return base.Channel.GetXmlRCDataWODSCV(request);
        }
        
        public System.Xml.Linq.XElement GetXmlRCDataWODSCV(string RCNo, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest inValue = new KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequestBody();
            inValue.Body.RCNo = RCNo;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetXmlRCDataWODSCV(inValue);
            return retVal.Body.GetXmlRCDataWODSCVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.GetXmlRCDataWODSCVAsync(KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest request) {
            return base.Channel.GetXmlRCDataWODSCVAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVResponse> GetXmlRCDataWODSCVAsync(string RCNo, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest inValue = new KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.GetXmlRCDataWODSCVRequestBody();
            inValue.Body.RCNo = RCNo;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).GetXmlRCDataWODSCVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.InsertRCAppTranResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.InsertRCAppTran(KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest request) {
            return base.Channel.InsertRCAppTran(request);
        }
        
        public System.Xml.Linq.XElement InsertRCAppTran(KACDC.NadaKacheriServiceReference.ArrayOfString args, byte[] Photo, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest inValue = new KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.InsertRCAppTranRequestBody();
            inValue.Body.args = args;
            inValue.Body.Photo = Photo;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            KACDC.NadaKacheriServiceReference.InsertRCAppTranResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).InsertRCAppTran(inValue);
            return retVal.Body.InsertRCAppTranResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.InsertRCAppTranResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.InsertRCAppTranAsync(KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest request) {
            return base.Channel.InsertRCAppTranAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.InsertRCAppTranResponse> InsertRCAppTranAsync(KACDC.NadaKacheriServiceReference.ArrayOfString args, byte[] Photo, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest inValue = new KACDC.NadaKacheriServiceReference.InsertRCAppTranRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.InsertRCAppTranRequestBody();
            inValue.Body.args = args;
            inValue.Body.Photo = Photo;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).InsertRCAppTranAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.UpdateRCGSCNo(KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest request) {
            return base.Channel.UpdateRCGSCNo(request);
        }
        
        public System.Xml.Linq.XElement UpdateRCGSCNo(KACDC.NadaKacheriServiceReference.ArrayOfString args, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest inValue = new KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequestBody();
            inValue.Body.args = args;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).UpdateRCGSCNo(inValue);
            return retVal.Body.UpdateRCGSCNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.UpdateRCGSCNoAsync(KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest request) {
            return base.Channel.UpdateRCGSCNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.UpdateRCGSCNoResponse> UpdateRCGSCNoAsync(KACDC.NadaKacheriServiceReference.ArrayOfString args, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest inValue = new KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.UpdateRCGSCNoRequestBody();
            inValue.Body.args = args;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).UpdateRCGSCNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponse KACDC.NadaKacheriServiceReference.WebServiceSoap.UpdateRCAgainstAppId(KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest request) {
            return base.Channel.UpdateRCAgainstAppId(request);
        }
        
        public System.Xml.Linq.XElement UpdateRCAgainstAppId(string AppId, string RCNo, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest inValue = new KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequestBody();
            inValue.Body.AppId = AppId;
            inValue.Body.RCNo = RCNo;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponse retVal = ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).UpdateRCAgainstAppId(inValue);
            return retVal.Body.UpdateRCAgainstAppIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponse> KACDC.NadaKacheriServiceReference.WebServiceSoap.UpdateRCAgainstAppIdAsync(KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest request) {
            return base.Channel.UpdateRCAgainstAppIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdResponse> UpdateRCAgainstAppIdAsync(string AppId, string RCNo, string Dept, string Flag1, string Flag2) {
            KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest inValue = new KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequest();
            inValue.Body = new KACDC.NadaKacheriServiceReference.UpdateRCAgainstAppIdRequestBody();
            inValue.Body.AppId = AppId;
            inValue.Body.RCNo = RCNo;
            inValue.Body.Dept = Dept;
            inValue.Body.Flag1 = Flag1;
            inValue.Body.Flag2 = Flag2;
            return ((KACDC.NadaKacheriServiceReference.WebServiceSoap)(this)).UpdateRCAgainstAppIdAsync(inValue);
        }
    }
}
